function [RAinit,RABPinit,RARinit,Rinit,BPinit,RAoutinit] = initsFromp(p)
    beta = p.vmax;
    delta = p.moff;
    eta = p.rdeg1;
    alpha = p.kdeg; %alpha
    omega = p.gamma; %omega
    gamma = p.mon; %gamma
    nu = p.jalpha; %nu
    lambda = p.jbeta; %lambda
    r = p.rdeg2; %r
    zeta = p.Vr; %zeta
    a = p.Vbp; %a
    u = p.bpdeg1; %u
    b = p.beta; %b
    c = p.kp; %c
    d = p.d; %d
    e = p.e; %e
    
    RAinit   = (beta*gamma*zeta*nu - r*delta*eta*lambda*omega + sqrt(4*r*beta*gamma*delta*zeta*(alpha+eta)*lambda*nu*omega + (beta*gamma*zeta*nu - r*delta*eta*lambda*omega)^2))/...
    (2*gamma*zeta*(alpha+eta)*nu);
    RABPinit = (1/2).*delta.^(-1).*(alpha+eta).^(-1).*nu.^(-1).*u.^(-1).*zeta.^( ...
      -1).*((-1).*omega.*(delta.*e.*eta.*lambda.*r+beta.*gamma.*nu.* ...
      zeta)+e.*(delta.*e.*(alpha+eta).*lambda.*r+beta.*gamma.*nu.*zeta)) ...
      .^(-1).*((-1).*a.*((-1).*delta.*e.^2.*(alpha+eta).*lambda.*r+ ...
      beta.*gamma.*nu.*omega.*zeta+e.*(delta.*eta.*lambda.*omega.*r+(-1) ...
      .*beta.*gamma.*nu.*zeta)).*((-1).*delta.*eta.*lambda.*omega.*r+ ...
      beta.*gamma.*nu.*zeta+(delta.^2.*eta.^2.*lambda.^2.*omega.^2.* ...
      r.^2+2.*beta.*delta.*(2.*alpha+eta).*gamma.*lambda.*nu.*omega.*r.* ...
      zeta+beta.^2.*gamma.^2.*nu.^2.*zeta.^2).^(1/2))+d.*((-1).*beta.* ...
      gamma.*nu.*omega.*zeta.*((-1).*delta.*eta.*lambda.*omega.*r+beta.* ...
      gamma.*nu.*zeta+(delta.^2.*eta.^2.*lambda.^2.*omega.^2.*r.^2+2.* ...
      beta.*delta.*(2.*alpha+eta).*gamma.*lambda.*nu.*omega.*r.*zeta+ ...
      beta.^2.*gamma.^2.*nu.^2.*zeta.^2).^(1/2))+e.*(beta.^2.*gamma.^2.* ...
      nu.^2.*zeta.^2+delta.*eta.*lambda.*omega.*r.*(delta.*eta.*lambda.* ...
      omega.*r+(-1).*(delta.^2.*eta.^2.*lambda.^2.*omega.^2.*r.^2+2.* ...
      beta.*delta.*(2.*alpha+eta).*gamma.*lambda.*nu.*omega.*r.*zeta+ ...
      beta.^2.*gamma.^2.*nu.^2.*zeta.^2).^(1/2))+beta.*gamma.*nu.*zeta.* ...
      (2.*alpha.*delta.*lambda.*omega.*r+(delta.^2.*eta.^2.*lambda.^2.* ...
      omega.^2.*r.^2+2.*beta.*delta.*(2.*alpha+eta).*gamma.*lambda.*nu.* ...
      omega.*r.*zeta+beta.^2.*gamma.^2.*nu.^2.*zeta.^2).^(1/2)))));
    RARinit  = (gamma*zeta*nu)/(r*delta*lambda) * RAinit;
    Rinit    = zeta/r;
    BPinit   = ((-2).*omega.*u.*(delta.*e.*eta.*lambda.*r+beta.*gamma.*nu.*zeta)+ ...
      2.*e.*u.*(delta.*e.*(alpha+eta).*lambda.*r+beta.*gamma.*nu.*zeta)) ...
      .^(-1).*(delta.*e.*lambda.*(2.*a.*e.*(alpha+eta)+(-1).*(2.*a+d).* ...
      eta.*omega).*r+beta.*gamma.*nu.*((2.*a+d).*e+(-2).*(a+d).*omega).* ...
      zeta+d.*e.*(4.*beta.*delta.*(alpha+eta).*gamma.*lambda.*nu.* ...
      omega.*r.*zeta+((-1).*delta.*eta.*lambda.*omega.*r+beta.*gamma.* ...
      nu.*zeta).^2).^(1/2));
    RAoutinit= (beta + c*RAinit)/b;
end